# Generated by Django 5.2.17 on 2026-10-01 08:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Wholesale purchase unit cost at time of sale', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Available inventory count (supports fractional units e.g. boxes)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10),
        ),
    ]
