# Generated by Django 5.2.17 on 2026-10-01 14:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transactionitem_cost_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='TindAI Sari-Sari Store', help_text='Official name of the sari-sari store', max_length=255)),
                ('caretaker_identity', models.CharField(default='Tindero / Tindera', help_text='Name or role of current store caretaker', max_length=255)),
                ('default_retail_markup_percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Default retail markup percentage applied to wholesale cost (e.g. 15.00 for 15%)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Configuration',
                'verbose_name_plural': 'Store Configuration',
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='single_store_config_record')],
            },
        ),
    ]
