# Generated by Django 5.2.17 on 2026-10-06 23:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_restockinvoice_alter_restockrun_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wholesaler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('branch', models.CharField(blank=True, default='', max_length=255)),
                ('contact_number', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wholesaler',
                'verbose_name_plural': 'Wholesalers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Customer debt balance after this payment', max_digits=10),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Customer debt balance before this payment', max_digits=10),
        ),
        migrations.AddField(
            model_name='restockinvoice',
            name='parse_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARSED', 'Parsed'), ('CONFIRMED', 'Confirmed')], default='CONFIRMED', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross profit = total_amount - total_cogs', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sync_status',
            field=models.CharField(choices=[('PENDING_OFFLINE', 'Pending Offline'), ('SYNCED', 'Synced')], default='SYNCED', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_cogs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total Cost of Goods Sold', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_number',
            field=models.CharField(blank=True, db_index=True, help_text='Unique human-readable transaction identifier e.g. TXN-YYYYMMDD-XXXX', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restockinvoice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restockinvoiceitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restockrun',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('initial_tingi_quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('remaining_tingi_quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit_cost_basis', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('invoice_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='core.restockinvoiceitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.product')),
            ],
            options={
                'verbose_name': 'Inventory Batch',
                'verbose_name_plural': 'Inventory Batches',
                'ordering': ['received_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('SALE', 'Sale'), ('RESTOCK', 'Restock'), ('SPOILAGE', 'Spoilage'), ('AUDIT_ADJUSTMENT', 'Audit Adjustment')], max_length=20)),
                ('quantity_change', models.DecimalField(decimal_places=4, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=10)),
                ('reference_id', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.product')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='restockinvoice',
            name='wholesaler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.wholesaler'),
        ),
    ]
